language: c

compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
install:
  - echo  "Reached Install Section"

script:
  - echo "Reached Script Section"
  - gcc   	InitialCode.c -o output
  - ./output
  
    #added section for cunit testing
  - echo "Reached Script Section - cunit_Sharan"
  - gcc   InitialCode.c -o cunit_Sharan -lcunit
  - ./cunit_Sharan
  - size cunit_Sharan
